import PropsRespuesta from '@/modules/aps/models/PropsRespuesta'
const PrimeraInfancia = {
    component: 'PrimeraInfancia',
    ref_seccion: 'primera_infancia',
    descripcion: 'Primera infancia',
    show: true,
    respuestas: {
        pi_peso_al_nacer: PropsRespuesta,
        pi_peso_actual: PropsRespuesta,
        pi_talla_al_nacer: PropsRespuesta,
        pi_talla_actual: PropsRespuesta,
        pi_valoracion_nutricional: PropsRespuesta,
        pi_desarrollo_lenguaje: PropsRespuesta,
        pi_desarrollo_motora: PropsRespuesta,
        pi_desarrollo_conducta: PropsRespuesta,
        pi_desarrollo_probelmas_visuales: PropsRespuesta,
        pi_desarrollo_problemas_auditivos: PropsRespuesta,
        pi_desparasitado: PropsRespuesta,
        pi_hospitalizacion_nacer: PropsRespuesta,
        pi_carnet_vacunacion: PropsRespuesta,
        pi_vacuna_bcg_rn: PropsRespuesta,
        pi_vacuna_polio_d1: PropsRespuesta,
        pi_vacuna_polio_d2: PropsRespuesta,
        pi_vacuna_polio_d3: PropsRespuesta,
        pi_vacuna_polio_r1: PropsRespuesta,
        pi_vacuna_polio_r2: PropsRespuesta,
        pi_vacuna_hepatitis_a: PropsRespuesta,
        pi_vacuna_hepatitis_b_rn: PropsRespuesta,
        pi_vacuna_influenza_estacional: PropsRespuesta,
        pi_vacuna_neumococo_d1: PropsRespuesta,
        pi_vacuna_neumococo_d2: PropsRespuesta,
        pi_vacuna_neumococo_d3: PropsRespuesta,
        pi_vacuna_rotavirus_d1: PropsRespuesta,
        pi_vacuna_rotavirus_d2: PropsRespuesta,
        pi_vacuna_fiebre_amarilla: PropsRespuesta,
        pi_vacuna_dpt_d1: PropsRespuesta,
        pi_vacuna_dpt_d2: PropsRespuesta,
        pi_vacuna_pentavalente_d1: PropsRespuesta,
        pi_vacuna_pentavalente_d2: PropsRespuesta,
        pi_vacuna_pentavalente_d3: PropsRespuesta,
        pi_vacuna_srp_d1: PropsRespuesta,
        pi_vacuna_srp_d2: PropsRespuesta,
        pi_vacuna_varicela: PropsRespuesta,
        pi_atencion_medica: PropsRespuesta,
        pi_atencion_enfermeria: PropsRespuesta,
        pi_atencion_lactancia: PropsRespuesta,
        pi_tsh: PropsRespuesta,
        pi_fluor: PropsRespuesta,
        pi_profilaxis: PropsRespuesta,
        pi_sellantes: PropsRespuesta,
        pi_higiene_bucal: PropsRespuesta,
        pi_caries: PropsRespuesta,
        pi_consulta_odontologica: PropsRespuesta,
    }
}

export default PrimeraInfancia